### ISSUE TITLE
Should room.send action be changed to send JSON object instead of string?

### ISSUE THREAD

**Issue by MikalDev** [colyseus/colyseus-construct3#11]
In 0.13.0 version of the plugin, changed the following for the Room Send action:

       this.room.send([type, JSON.parse(data)]);
to
       this.room.send(type, message);

Is this as intended? It seems like sending a string instead of a JSON object doesn't match the updated Agar example. (I had to change the Agar server side to JSON.parse the string on the server side, instead of using the MouseMessage interface definition.)

should the above change to: this.room.send(type, JSON.parse(message)) ?

**Comment by endel** [comment]
Hi @MikalDev, thanks for taking the time to check this. I was uncertain about this change, but it seems we should roll this back indeed.

I'm wondering if we'd have the flexibility to pass anything to the "Send" method this way. Plain strings, plain numbers, or a JSON object. I'm new to Construct, and apparently it's only possible to do `JSON.ToCompactString()`, can you confirm if Construct is able to pass a JSON object reference without it being stringified? 

Cheers!

**Comment by MikalDev** [comment]
I think in general this is an overall server/client design decision. The current way in 0.13.0 plugin can also work. It required a change on the server to do the JSON.parse() from the string sent, which is ok. 

It seems useful to keep the behavior similar with other clients, for example does the pixjs client send a JSON object? From the example server code for the pixjs example it seems like it might. Do other clients work in similar ways, or do the interfaces allow messages with string, number, object, etc.?

In terms of C3, an idea of one way to pass in JSON would be to change the 'message' to accept only JSON objects. This does feel a bit more constraining, since it's pretty easy to also form a JSON string using C3 string operations and it's easy to use JSON.ToCompactString().

I imagine MsgPack compression also works well on string that are formatted as JSON, so it would not hurt too much there.

So, in the end, my recommendation is that if other clients are all passing JSON objects and in general Colyseus servers expect that, the C3 client should also. If they are not, then I think using 'any' or 'string'  is fine, up to the server code to interpret it properly.

Another C3 quirk to be aware of - if ACE IDs are changed and those ACEs are used in old projects. The older projects will not open with a new version of the plugin. In the 0.13.0 update, I had to open with an older version of the plugin, delete the On Error event/condition, save, then I could open with the new plugin (and add back the On Error event.)

**Comment by endel** [comment]
Thanks for your feedback @MikalDev, as all messages are seamlessly encoded using msgpack under the hood on all clients, I've changed now the `Send message` to accept both string and number types (`any`), and added a new `Send JSON message` action, which you could pass a `JSON.ToCompactString()` (that is going to be parsed, and then encoded again as msgpack to be sent to the server) 🙏
