### ISSUE TITLE
TBD: Allow to attach callbacks on deep structures

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus-construct3#15]
In pure JavaScript, to be able to catch `players.xxxx.gold`, for example, you would do this:

```typescript
state.players.onAdd = (player, id) => {
  player.onChange = (changes) => {
    changes.forEach((change) => {
      change.field // gold
      change.value // 10
    })
  }
}
```

C3 only seems to allow adding events statically at layout startup, so we can't register events for each player by id.

(if we could register "On Change" for each `[id]`, like `entities.fh91h3f.gold` it would work, but it doesn't seem to be possible atm)

> "@endel How about an action to register a on change path, then a generic on change condition with an expression that identifies the Path that changed, a sub condition could deal with the particular path if needed." - @MikalDev 

> "Also an action to unregister a on change path" - @MikalDev

**Comment by MikalDev** [comment]
One idea was to add a register ACE that did the following:
```
registerOnChange(path)
{
    state[path].onAdd = (entry, id) => {
    entry.onChange = (changes) => {
      changes.forEach((change) => {
        self.lastPreviousValue = change.previousValue;
        self.lastField = change.field // gold
        self.lastValue = change.value // 10
        self.Trigger(C3.Plugins.Colyseus.Cnds.OnSchemaFieldChange);
      })
    }
  }
}
```

Though this may not work, I can't quite remember how C3 will handle multiple triggers in one tick (e.g. multiple changes in one tick.) I think it will be ok, if it is defined as a regular trigger, not a fake trigger.

**Comment by endel** [comment]
Thank you @MikalDev, on the latest there is a `"On change at"` condition that can now handle these! 🙏
