### ISSUE TITLE
Missing Serializer: none

### ISSUE THREAD

**Issue by breakerh** [colyseus/colyseus-construct3#16]
I've been getting the following error since the update from 13.x to 14.x..
Both the server and client have been updated.

How can i solve this?
![image](https://user-images.githubusercontent.com/2008632/114781547-1b539c00-9d79-11eb-9643-369cad6115cb.png)

**Comment by endel** [comment]
Hi @breakerh, thanks for letting me know, I've just uploaded a new version using the latest colyseus.js + schema. Can you please check if that fixes this error? https://www.construct.net/en/make-games/addons/111/colyseus-multiplayer-sdk

**Comment by breakerh** [comment]
Sorry for the BIG delay. But yeah you've fixed it thank you so much :)
