### ISSUE TITLE
can't minify c3 project because of Colyseus addon

### ISSUE THREAD

**Issue by F3der1co** [colyseus/colyseus-construct3#30]
To reproduce: export a project that has colyseus added with minification.
Error message:
`working/810799356/scripts/c3runtime.js:8929:47: ERROR - [JSC_REASSIGNED_CONSTANT] Constant reassigned: i
  8929|         for (const i = 0; i < segments.length; i++) {`
  
  This seems to be line 16 in conditions.js:
  
![image](https://github.com/user-attachments/assets/746555a5-4f6e-43c5-a0d2-35349de85403)
I assume changing the const to let should fix it.

**Comment by endel** [comment]
Hi @F3der1co, thank you for the feedback - can you please try version `0.15.0.14` that I just released? 🙏

**Comment by F3der1co** [comment]
Minification works now, thanks a lot for the quick fix!
