### ISSUE TITLE
client not referenced, maybe this.client?

### ISSUE THREAD

**Issue by tatosgames** [colyseus/colyseus-construct3#5]
https://github.com/colyseus/colyseus-construct3/blob/15e6a4fa6f913558214073e96ed8226023e1a524/plugin/c3runtime/actions.js#L35

**Comment by endel** [comment]
Thanks for spotting that @tatosgames, I've just published `0.9.5.1` here: https://www.construct.net/en/make-games/addons/111/colyseus-multiplayer
